name: active_driver_new
description: A Flutter app that detects driver drowsiness in real-time.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.5+5
  tflite_flutter: ^0.11.0
  permission_handler: ^11.0.1
  audioplayers: ^5.2.1
  vibration: ^3.1.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/modelo_somnolencia_4clases.tflite
    - assets/labels.txt
    - assets/alerta.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
